[package]
name = "starlingmonkey-spec-scaffold"
version = "0.1.0"
repository = "https://github.com/tschneidereit/starlingmonkey-spec-scaffold"
license = "Apache-2.0 WITH LLVM-exception"
authors = ["The StarlingMonkey project contributors"]
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
heck = "0.5"
scraper = "0.27.0"
ureq = "3.3"
weedle = { version = "5.0", package = "weedle2" }
